services:
  tool-api-mapper:
    build: ./tool-api-mapper
    container_name: tool-api-mapper
    environment:
      - OLLAMA_HOST=http://model-runner:11434
    ports:
      - "5000:5000"
    depends_on:
      - model-runner
      - mcp-tool
    networks:
      - mcp_try
  model-runner:
    build: ./model-runner
    container_name: model-runner
    ports:
      - "11434:11434"
    networks:
      - mcp_try

  mcp-tool:
    build: ./mcp-tool
    container_name: mcp-tool
    depends_on:
      - result-query-service
    ports:
      - "8080:8080"
    networks:
      - mcp_try

  result-query-service:
    build: result-query-service/.
    container_name: result-query-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/testdb
    depends_on:
      - db
    networks:  
      - mcp_try

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  mcp_try:
    driver: bridge 

volumes:
  pgdata: